:!UTF-8
select 
   0 as LP,
   POZYCJA Struktura,
   KTM,
   N as "Nazwa",
   JM as "jm",
   IL2 as "Ilość",
   SYM_PARS as "Partia surowca",
   SYM_PAR as "Partia wyrobu/półwyrobu",
   W02_PD as "PD/BatchCode",
   SCEAN as "Identyfikator partii",
   TW as "Termin ważności",
   SYM_DOK as "Symbol dokumentu",
   POZ_DOK as "Pozycja doumentu",
   DATA_DOK as "Data dokumentu",
   ZPARN,
   W01_PART,
   PLUS,
   P1,
   P2,
   P3,
   P4,
   P5,
   P6,
   P7,
   P8,
   P9,
   P10 
from :_a
order by P1,P2,P3,P4,P5,P6,P7,P8,P9,P10