:!UTF-8
SELECT 0 as "LP", P.T as "Nr teczki", P.ZA as "Zatrudniony(a)", UD_SKL.SYMBOL as "Wydział", UD_SKL.OPIS as "Wydział - opis", OSOBA.NAZWISKO as "Nazwisko", OSOBA.PIERWSZE as "Imię", ZALACZ.ZAL_NAME as "Nazwa zalacznika", ZALACZ.POTW as "Czy pobrany", ZALACZ.POB_D as "Data pobrania"
FROM ZALACZ
JOIN OSOBA USING (ZALACZ.OSOBA,OSOBA.REFERENCE)
JOIN P USING (ZALACZ.P,P.REFERENCE)
JOIN UD_SKL USING (P.WYDZIAL, UD_SKL.REFERENCE)
WHERE ZALACZ.ZAL_NAME like 'PIT11%2023%'
ORDER BY 6,7,10,9,8,5,4,3,2,1