:!UTF-8
praclimoq@1@Uprawnienia@F@0@
praclimoq@1@@
praclimoq@1@exec('dostepne_p','schemat','PKD',__F_ZATR.P,'*')@
praclimoq@1@@
praclimoq@1@@
praclimoq@1@@
praclimoq@1@@
praclimoq@2@Data@D@0@
praclimoq@2@@
praclimoq@2@date()@
praclimoq@2@@
praclimoq@2@@
praclimoq@2@@
praclimoq@2@@
praclistq@1@Uprawnienia@F@0@
praclistq@1@@
praclistq@1@exec('dostepne_p','schemat','PKD',__F_ZATR.P,'*')@
praclistq@1@@
praclistq@1@@
praclistq@1@@
praclistq@1@@
praclistq@2@Data@D@0@
praclistq@2@@
praclistq@2@date()@
praclistq@2@@
praclistq@2@@
praclistq@2@@
praclistq@2@@
pracpobr@1@Uprawnienia@F@0@
pracpobr@1@@
pracpobr@1@exec('dostepne_p_parses','schemat','PKD')@
pracpobr@1@@
pracpobr@1@@
pracpobr@1@@
pracpobr@1@@
