:!UTF-8
select 
	0 as LP,
                      WYDZIAL as "Wydział",
	WKTM "Indeks produktu",
	WN "Nazwa produktu",
	NRK "Numer karty technologicznej",
	WER "Wersja karty technologicznej",
	XJM "Na ile projektowana jest technologia",
 	DEFAULT "Domyślna karta dla danego wyrobu",
	SKTM "Indeks surowca",
	SN "Nazwa surowca",
	WARB "Norma materiałowa brutto",
	WARN "Norma materiałowa netto",
	UNB "Uzysk (netto / brutto)",
	XJMP "Procentowa zawartość surowca",
	OPIS "Opis karty",
	STAN "Stan karty - bez akceptacji (N), częściowo zaakceptowana (P), zaakcetowana(T)",
	NROP "Numer operacji",
	KOD "Kod operacji",
	NA "Nazwa operacji",
	DFLT_KTL "Domyślna technologia na półfabrykat",
	DWARB "Norma brutto w dodatkowej jednostce miary",
	DWARN "Norma netto w dodatkowej jednostce miary",
	FORMB "Formuła dla normy brutto",
	FORMN "Formuła dla normy netto",
	LIMIT "Surowiec limitowany (T) - nielimitowany (N)",
	MAG "Czy półprodukt jest pobierany z magazynu",
	PODST "Surowiec podstawowy (T,N)",
	POW "Surowiec powierzony (T,N)",
	ROZ "Surowiec rozliczany na kiosku",
	SO "Surowiec (S) - odpad (O)"
from :_a
order by 1
