:!UTF-8
select
   0 as LP,
                     WYDZIAL as "Wydział",
   NRK "Numer karty technologicznej",
   WER "Wersja karty technologicznej",
   OPIS "Opis karty",
   WKTM "Indeks produktu",
   WN "Nazwa produktu",
   GRP6 "Klient",
   BRYG "Operację wykonuje brygada",
   FIX_NORM "Stała norma czasowa niezależna od ilości",
   MTIME "Czas maszynowy",
   STAN "Stan karty - bez akceptacji (N), częściowo zaakceptowana (P), zaakcetowana(T)",
    DEFAULT "Domyślna karta dla danego wyrobu",
   XJM "Na ile projektowana jest technologia",
   NROP "Numer operacji",
   T "Dokument raportujący produkcję",
   NTIME "Norma czasowa na wykonanie operacji",
   GRPOJ "Stanowisko/Gniazdo",
   TTM "O ile ta operacja będzie odsunięta od poprzedniej",
   NAZWA "Nazwa gniazda produkcyjnego",
   SYMBOL "Symbol gniazda produkcyjnego",
   KOD "Kod operacji",
   NA "Nazwa operacji",
   TPZ "Operacja jest Czasem Przygotowawczo Zakończeniowym (TPZ)",
   KS "Kod stanowiska",
   NS "Nazwa stanowiska"
from :_a
order by 1
