:!UTF-8
select
0 as LP,
KH.KOD KodK,
KH.SKR NazwaK,
FAKS.NIP NipK,
FAKS.NIP_UE NipKUE,
M.KTM Kod,
M.N Nazwa,
M.REFERENCE MRef,
M.GRP1 MGrp1,
sum(case when substr(to_string(FAKS.DW),6,2)='01' then FAP.IL else 0 end) as "01i",
sum(case when substr(to_string(FAKS.DW),6,2)='01' then FAP.WN else 0 end) as "01w",
(sum(case when substr(to_string(FAKS.DW),6,2)='01' then FAP.IL else 0 end))*M.WN as "01n",
sum(case when substr(to_string(FAKS.DW),6,2)='02' then FAP.IL else 0 end) as "02i",
sum(case when substr(to_string(FAKS.DW),6,2)='02' then FAP.WN else 0 end) as "02w",
(sum(case when substr(to_string(FAKS.DW),6,2)='02' then FAP.IL else 0 end))*M.WN as "02n",
sum(case when substr(to_string(FAKS.DW),6,2)='03' then FAP.IL else 0 end) as "03i",
sum(case when substr(to_string(FAKS.DW),6,2)='03' then FAP.WN else 0 end) as "03w",
(sum(case when substr(to_string(FAKS.DW),6,2)='03' then FAP.IL else 0 end))*M.WN as "03n",
sum(case when substr(to_string(FAKS.DW),6,2)='04' then FAP.IL else 0 end) as "04i",
sum(case when substr(to_string(FAKS.DW),6,2)='04' then FAP.WN else 0 end) as "04w",
(sum(case when substr(to_string(FAKS.DW),6,2)='04' then FAP.IL else 0 end))*M.WN as "04n",
sum(case when substr(to_string(FAKS.DW),6,2)='05' then FAP.IL else 0 end) as "05i",
sum(case when substr(to_string(FAKS.DW),6,2)='05' then FAP.WN else 0 end) as "05w",
(sum(case when substr(to_string(FAKS.DW),6,2)='05' then FAP.IL else 0 end))*M.WN as "05n",
sum(case when substr(to_string(FAKS.DW),6,2)='06' then FAP.IL else 0 end) as "06i",
sum(case when substr(to_string(FAKS.DW),6,2)='06' then FAP.WN else 0 end) as "06w",
(sum(case when substr(to_string(FAKS.DW),6,2)='06' then FAP.IL else 0 end))*M.WN as "06n",
sum(case when substr(to_string(FAKS.DW),6,2)='07' then FAP.IL else 0 end) as "07i",
sum(case when substr(to_string(FAKS.DW),6,2)='07' then FAP.WN else 0 end) as "07w",
(sum(case when substr(to_string(FAKS.DW),6,2)='07' then FAP.IL else 0 end))*M.WN as "07n",
sum(case when substr(to_string(FAKS.DW),6,2)='08' then FAP.IL else 0 end) as "08i",
sum(case when substr(to_string(FAKS.DW),6,2)='08' then FAP.WN else 0 end) as "08w",
(sum(case when substr(to_string(FAKS.DW),6,2)='08' then FAP.IL else 0 end))*M.WN as "08n",
sum(case when substr(to_string(FAKS.DW),6,2)='09' then FAP.IL else 0 end) as "09i",
sum(case when substr(to_string(FAKS.DW),6,2)='09' then FAP.WN else 0 end) as "09w",
(sum(case when substr(to_string(FAKS.DW),6,2)='09' then FAP.IL else 0 end))*M.WN as "09n",
sum(case when substr(to_string(FAKS.DW),6,2)='10' then FAP.IL else 0 end) as "10i",
sum(case when substr(to_string(FAKS.DW),6,2)='10' then FAP.WN else 0 end) as "10w",
(sum(case when substr(to_string(FAKS.DW),6,2)='10' then FAP.IL else 0 end))*M.WN as "10n",
sum(case when substr(to_string(FAKS.DW),6,2)='11' then FAP.IL else 0 end) as "11i",
sum(case when substr(to_string(FAKS.DW),6,2)='11' then FAP.WN else 0 end) as "11w",
(sum(case when substr(to_string(FAKS.DW),6,2)='11' then FAP.IL else 0 end))*M.WN as "11n",
sum(case when substr(to_string(FAKS.DW),6,2)='12' then FAP.IL else 0 end) as "12i",
sum(case when substr(to_string(FAKS.DW),6,2)='12' then FAP.WN else 0 end) as "12w",
(sum(case when substr(to_string(FAKS.DW),6,2)='12' then FAP.IL else 0 end))*M.WN as "12n"
from @FAP
   left join M using (FAP.M,M.REFERENCE)
   left join @FAKS using (FAP.FAKS,FAKS.REFERENCE)
   left join KH using (FAKS.KH,KH.REFERENCE)
where substr(to_string(FAKS.DW),1,4)=':_b'  and FAKS.AKC='T' and KH.KOD like ':_a%' and M.REFERENCE = FAP.M
group by KH.KOD,KH.SKR,FAKS.NIP,FAKS.NIP_UE,M.KTM,M.N,FAP.WN,M.WN,M.REFERENCE,M.GRP1