:!UTF-8
err_nrko@1@Uprawnienia@F@0@
err_nrko@1@@
err_nrko@1@exec('dostepne_p_parses','schemat','PKD')@
err_nrko@1@@
err_nrko@1@@
err_nrko@1@@
err_nrko@1@@
pit12@1@Uprawnienia@F@0@
pit12@1@@
pit12@1@exec('dostepne_p_parses','schemat','PKD')@
pit12@1@@
pit12@1@@
pit12@1@@
pit12@1@@
pit12@2@Rok podatkowy@I@0@
pit12@2@@
pit12@2@date()~1@
pit12@2@@
pit12@2@@
pit12@2@@
pit12@2@@
prac_pko@1@Uprawnienia@F@0@
prac_pko@1@@
prac_pko@1@exec('dostepne_p_parses','schemat','PKD')@
prac_pko@1@@
prac_pko@1@@
prac_pko@1@@
prac_pko@1@@
prachur2@1@Uprawnienia@F@0@
prachur2@1@@
prachur2@1@exec('dostepne_p_parses','schemat','PKD')@
prachur2@1@@
prachur2@1@@
prachur2@1@@
prachur2@1@@
prachur2@2@Data@D@0@
prachur2@2@@
prachur2@2@date()@
prachur2@2@@
prachur2@2@@
prachur2@2@@
prachur2@2@@
prachur2@3@Numer@F@0@
prachur2@3@@
prachur2@3@__RUB.sys_sql(114)@
prachur2@3@@
prachur2@3@@
prachur2@3@@
prachur2@3@@
prachurl@1@Uprawnienia@F@0@
prachurl@1@@
prachurl@1@exec('dostepne_p_parses','schemat','PKD')@
prachurl@1@@
prachurl@1@@
prachurl@1@@
prachurl@1@@
prachurl@2@Data@D@0@
prachurl@2@@
prachurl@2@date()@
prachurl@2@@
prachurl@2@@
prachurl@2@@
prachurl@2@@
prachurl@3@Numer@F@0@
prachurl@3@@
prachurl@3@__RUB.sys_sql(112)@
prachurl@3@@
prachurl@3@@
prachurl@3@@
prachurl@3@@
praclist@1@Uprawnienia@F@0@
praclist@1@@
praclist@1@exec('dostepne_p','schemat','PKD',__PARSES.getVal('F_ZATR').KOD,,__PARSES.getVal('JednostkaOrganizacyjna').SYMBOL)@
praclist@1@@
praclist@1@@
praclist@1@@
praclist@1@@
praclist@2@Data@D@0@
praclist@2@@
praclist@2@date()@
praclist@2@@
praclist@2@@
praclist@2@@
praclist@2@@
praczast@1@Uprawnienia@F@0@
praczast@1@@
praczast@1@exec('dostepne_p_parses','schemat','PKD')@
praczast@1@@
praczast@1@@
praczast@1@@
praczast@1@@
praczast@2@Data@D@0@
praczast@2@@
praczast@2@date()@
praczast@2@@
praczast@2@@
praczast@2@@
praczast@2@@
praczatr@1@Uprawnienia@F@0@
praczatr@1@@
praczatr@1@exec('dostepne_p','schemat','PKD',__PARSES.getVal('F_ZATR').KOD,,__PARSES.getVal('JednostkaOrganizacyjna').SYMBOL)@
praczatr@1@@
praczatr@1@@
praczatr@1@@
praczatr@1@@
praczatr@2@Od dnia@D@0@
praczatr@2@@
praczatr@2@date()@
praczatr@2@@
praczatr@2@@
praczatr@2@@
praczatr@2@@
praczatr@3@Do dnia@D@0@
praczatr@3@@
praczatr@3@date()@
praczatr@3@@
praczatr@3@@
praczatr@3@@
praczatr@3@@
praczwol@1@Uprawnienia@F@0@
praczwol@1@@
praczwol@1@exec('dostepne_p','schemat','PKD',__PARSES.getVal('F_ZATR').KOD,,__PARSES.getVal('JednostkaOrganizacyjna').SYMBOL)@
praczwol@1@@
praczwol@1@@
praczwol@1@@
praczwol@1@@
praczwol@2@Od dnia@D@0@
praczwol@2@@
praczwol@2@date()@
praczwol@2@@
praczwol@2@@
praczwol@2@@
praczwol@2@@
praczwol@3@Do dnia@D@0@
praczwol@3@@
praczwol@3@date()@
praczwol@3@@
praczwol@3@@
praczwol@3@@
praczwol@3@@
umloj@1@Uprawnienia@F@0@
umloj@1@@
umloj@1@exec('dostepne_p_parses','schemat','PKD')@
umloj@1@@
umloj@1@@
umloj@1@@
umloj@1@@
umloj@2@Stan na dzień@D@0@
umloj@2@@
umloj@2@date(,,0)@
umloj@2@@
umloj@2@@
umloj@2@@
umloj@2@@
