:!UTF-8
licz_pod@1@Uprawnienia@F@0@
licz_pod@1@@
licz_pod@1@exec('dostepne_p_parses','schemat','PPL')@
licz_pod@1@@
licz_pod@1@@
licz_pod@1@@
licz_pod@1@@
licz_pod@2@Rok podatkowy@I@0@
licz_pod@2@@
licz_pod@2@date()~1@
licz_pod@2@@
licz_pod@2@@
licz_pod@2@@
licz_pod@2@@
realrycz@1@Uprawnienia@F@0@
realrycz@1@@
realrycz@1@exec('dostepne_p_parses','schemat','PPL')@
realrycz@1@@
realrycz@1@@
realrycz@1@@
realrycz@1@@
realrycz@2@Rok@I@0@
realrycz@2@@
realrycz@2@date()~1@
realrycz@2@@
realrycz@2@@
realrycz@2@@
realrycz@2@chk_fld@
zal_auto@1@Uprawnienia@F@0@
zal_auto@1@@
zal_auto@1@exec('dostepne_p_parses','schemat','PPL')@
zal_auto@1@@
zal_auto@1@@
zal_auto@1@@
zal_auto@1@@
zal_auto@2@Data od@D@0@
zal_auto@2@@
zal_auto@2@date()@
zal_auto@2@@
zal_auto@2@@
zal_auto@2@@
zal_auto@2@@
zal_auto@3@Data do@D@0@
zal_auto@3@@
zal_auto@3@date()@
zal_auto@3@@
zal_auto@3@@
zal_auto@3@@
zal_auto@3@@
zal_potr@1@Uprawnienia@F@0@
zal_potr@1@@
zal_potr@1@exec('dostepne_p_parses','schemat','PPL')@
zal_potr@1@@
zal_potr@1@@
zal_potr@1@@
zal_potr@1@@
zal_potr@2@Od dnia@D@0@
zal_potr@2@@
zal_potr@2@date()@
zal_potr@2@@
zal_potr@2@@
zal_potr@2@@
zal_potr@2@@
zal_potr@3@Do dnia@D@0@
zal_potr@3@@
zal_potr@3@date()@
zal_potr@3@@
zal_potr@3@@
zal_potr@3@@
zal_potr@3@@
zlec_oso@1@Uprawnienia@F@0@
zlec_oso@1@@
zlec_oso@1@exec('dostepne_p_parses','schemat','PPL')@
zlec_oso@1@@
zlec_oso@1@@
zlec_oso@1@@
zlec_oso@1@@
zlec_oso@2@Rok@I@0@
zlec_oso@2@@
zlec_oso@2@date()~1@
zlec_oso@2@@
zlec_oso@2@@
zlec_oso@2@@
zlec_oso@2@chk_fld@
zlec_oso@3@Miesiąc@I@0@
zlec_oso@3@@
zlec_oso@3@date()~2@
zlec_oso@3@@
zlec_oso@3@@
zlec_oso@3@@
zlec_oso@3@@
