:!UTF-8
rdo_list@1@Data przyjęcia od@D@0@
rdo_list@1@@
rdo_list@1@@
rdo_list@1@@
rdo_list@1@@
rdo_list@1@@
rdo_list@1@@
rdo_list@2@Data przyjęcia do@D@0@
rdo_list@2@@
rdo_list@2@@
rdo_list@2@@
rdo_list@2@@
rdo_list@2@@
rdo_list@2@@
rdo_list@3@Kontrahent@S@50@
rdo_list@3@@
rdo_list@3@exec('no_limit','sql')@
rdo_list@3@@
rdo_list@3@@
rdo_list@3@exec('kh','sql')@
rdo_list@3@exec('f3_only','sql')@
rdo_list@4@Towar/Usługa@S@50@
rdo_list@4@@
rdo_list@4@exec('no_limit','sql')@
rdo_list@4@@
rdo_list@4@@
rdo_list@4@exec('tow','sql')@
rdo_list@4@exec('f3_only','sql')@
rdo_stat@1@Data przyjęcia od@D@0@
rdo_stat@1@@
rdo_stat@1@@
rdo_stat@1@@
rdo_stat@1@@
rdo_stat@1@@
rdo_stat@1@@
rdo_stat@2@Data przyjęcia do@D@0@
rdo_stat@2@@
rdo_stat@2@@
rdo_stat@2@@
rdo_stat@2@@
rdo_stat@2@@
rdo_stat@2@@
rdo_stat@3@Kontrahent@S@50@
rdo_stat@3@@
rdo_stat@3@exec('no_limit','sql')@
rdo_stat@3@@
rdo_stat@3@@
rdo_stat@3@exec('kh','sql')@
rdo_stat@3@exec('f3_only','sql')@
rdo_stat@4@Towar/Usługa@S@50@
rdo_stat@4@@
rdo_stat@4@exec('no_limit','sql')@
rdo_stat@4@@
rdo_stat@4@@
rdo_stat@4@exec('tow','sql')@
rdo_stat@4@exec('f3_only','sql')@
rek_list@1@Data przyjęcia od@D@0@
rek_list@1@@
rek_list@1@@
rek_list@1@@
rek_list@1@@
rek_list@1@@
rek_list@1@@
rek_list@2@Data przyjęcia do@D@0@
rek_list@2@@
rek_list@2@@
rek_list@2@@
rek_list@2@@
rek_list@2@@
rek_list@2@@
rek_list@3@Kontrahent@S@50@
rek_list@3@@
rek_list@3@exec('no_limit','sql')@
rek_list@3@@
rek_list@3@@
rek_list@3@exec('kh','sql')@
rek_list@3@exec('f3_only','sql')@
rek_list@4@Towar/Usługa@S@50@
rek_list@4@@
rek_list@4@exec('no_limit','sql')@
rek_list@4@@
rek_list@4@@
rek_list@4@exec('tow','sql')@
rek_list@4@exec('f3_only','sql')@
rek_stat@1@Data przyjęcia od@D@0@
rek_stat@1@@
rek_stat@1@@
rek_stat@1@@
rek_stat@1@@
rek_stat@1@@
rek_stat@1@@
rek_stat@2@Data przyjęcia do@D@0@
rek_stat@2@@
rek_stat@2@@
rek_stat@2@@
rek_stat@2@@
rek_stat@2@@
rek_stat@2@@
rek_stat@3@Kontrahent@S@50@
rek_stat@3@@
rek_stat@3@exec('no_limit','sql')@
rek_stat@3@@
rek_stat@3@@
rek_stat@3@exec('kh','sql')@
rek_stat@3@exec('f3_only','sql')@
rek_stat@4@Towar/Usługa@S@50@
rek_stat@4@@
rek_stat@4@exec('no_limit','sql')@
rek_stat@4@@
rek_stat@4@@
rek_stat@4@exec('tow','sql')@
rek_stat@4@exec('f3_only','sql')@
zgl_list@1@Status rejestracji@S@50@
zgl_list@1@'u!'@
zgl_list@1@exec('remstat_def','sql')@
zgl_list@1@@
zgl_list@1@@
zgl_list@1@exec('remstat_f3','sql')@
zgl_list@1@exec('remstat_po','sql')@
zgl_stat@1@Status rejestracji@S@50@
zgl_stat@1@'u!'@
zgl_stat@1@exec('remstat_def','sql')@
zgl_stat@1@@
zgl_stat@1@@
zgl_stat@1@exec('remstat_f3','sql')@
zgl_stat@1@exec('remstat_po','sql')@
zgl_stat@2@Zasób@S@25@
zgl_stat@2@'u!'@
zgl_stat@2@'*'@
zgl_stat@2@@
zgl_stat@2@@
zgl_stat@2@exec('remzasob_f3','sql')@
zgl_stat@2@exec('remzasob_po','sql',1)@
zgl_stat@3@Awaria od@D@0@
zgl_stat@3@@
zgl_stat@3@date(0,0,0)@
zgl_stat@3@@
zgl_stat@3@@
zgl_stat@3@@
zgl_stat@3@@
zgl_stat@4@Awaria do@D@0@
zgl_stat@4@@
zgl_stat@4@date(0,0,0)@
zgl_stat@4@@
zgl_stat@4@@
zgl_stat@4@@
zgl_stat@4@@
